version: '2'

services:
  mongodb1:
    image: larsla/mongo-armv7l
    ports:
      - "27018:27017"
      - "28018:28017"
    restart: unless-stopped
    environment:
      REPLICA_SET: "rs"
      MONGODB_PASS: test
    networks:
      default:
        aliases:
          - mongodb1

  mongodb2:
    image: larsla/mongo-armv7l
    ports:
      - "27018:27017"
      - "28018:28017"
    restart: unless-stopped
    environment:
      REPLICA_SET: "rs"
      MONGODB_PASS: test
    networks:
      default:
        aliases:
          - mongodb2

  mongodb3:
    image: larsla/mongo-armv7l
    ports:
      - "27018:27017"
      - "28018:28017"
    restart: unless-stopped
    environment:
      REPLICA_SET: "rs"
      MONGODB_PASS: test
    networks:
      default:
        aliases:
          - mongodb3

  mongosetup:
    image: larsla/mongo-armv7l
    entrypoint: "/setup_replset.sh"
    environment:
      REPLICA_SET: "rs"
      MONGODB_PASS: test
