version: '2'

services:
  mongodb1:
    image: larsla/mongo-armv7l
    ports:
      - "27018:27017"
      - "28018:28017"
    restart: unless-stopped
    environment:
      REPLICA_SET: "rs"
      MONGODB_PASS: test
    volumes:
      - mongodb1:/data/db
    networks:
      - mongodb

  mongodb2:
    image: larsla/mongo-armv7l
    ports:
      - "27018:27017"
      - "28018:28017"
    restart: unless-stopped
    environment:
      REPLICA_SET: "rs"
      MONGODB_PASS: test
    volumes:
      - mongodb2:/data/db
    networks:
      - mongodb

  mongodb3:
    image: larsla/mongo-armv7l
    ports:
      - "27018:27017"
      - "28018:28017"
    restart: unless-stopped
    environment:
      REPLICA_SET: "rs"
      MONGODB_PASS: test
    volumes:
      - mongodb3:/data/db
    networks:
      - mongodb

  mongosetup:
    image: larsla/mongo-armv7l
    entrypoint: "/setup_replset.sh"
    environment:
      REPLICA_SET: "rs"
      MONGODB_PASS: test
      MONGODB1: "${COMPOSE_PROJECT_NAME}_mongodb1_1"
      MONGODB2: "${COMPOSE_PROJECT_NAME}_mongodb2_1"
      MONGODB3: "${COMPOSE_PROJECT_NAME}_mongodb3_1"
    networks:
      - mongodb

volumes:
  mongodb1:
  mongodb2:
  mongodb3:

networks:
  mongodb:
